apiVersion: v1
kind: Service
metadata:
  name: rolling-update-service
  namespace: rolling-ns
spec:
  selector:
    app: candy-shop
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000